//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCoupon
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int CouponId { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Order Order { get; set; }
    }
}
